services:
  auth:
    build:
      context: ./auth
    volumes:
      - ./auth/auth.py:/app/auth.py
  traefik:
    image: traefik:v2.11
    command:
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "8080:80"
      - "8081:8080" # Traefik dashboard
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    depends_on:
      - auth