http:
  routers:
    health-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: health-service
      middlewares:
        - auth-middleware

  services:
    health-service:
      loadBalancer:
        servers:
          - url: "http://auth:5000"

  middlewares:
    auth-middleware:
      forwardAuth:
        address: "http://auth:5000/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "x-pretest"